### ISSUE TITLE
this is most excellent. can I put it on marmalade?

### ISSUE THREAD

**Issue by nicferrier** [VincentToups/shadchen-el#3]

**Comment by VincentToups** [comment]
Nic, sure - but I keep meaning to go back and clean it up a bit.  It is a bit messier than I would like!

**Comment by nicferrier** [comment]
Also, you should go and help here:

https://github.com/magnars/dash.el/pull/67#issuecomment-57623276

Well, I think you should anyway.

**Comment by nicferrier** [comment]
Ha. Issue #1 shows that it's already there. You'll have to update it. Let me know of any problem.
