### ISSUE TITLE
any chance of another release?

### ISSUE THREAD

**Issue by nicferrier** [VincentToups/shadchen-el#9]
There were some stupid bugs in 1.1 (to do with lexical-binding being pulled put out) so it would be good to have those two things in there as a release.

You can release really easily with marmalade through your Emacs with the marmalade-upload package, which is available on marmalade (obviously).

**Comment by VincentToups** [comment]
Just uploaded v 1.2 and I added you to the contributors list in the package
description.  Thanks for pushing on this project!

**Comment by nicferrier** [comment]
Btw - the version here is still showing 1.0 - it should be 1.1. So you've got to bump it in the source.

Cheers!

**Comment by VincentToups** [comment]
Definitely did.  Maybe the cache issue?

**Comment by nicferrier** [comment]
I meant in Github.

**Comment by VincentToups** [comment]
Just pushed

**Comment by nicferrier** [comment]
Awesome!
